### ISSUE TITLE
Example apps don't work

### ISSUE THREAD

**Issue by azazel75** [rwl/muntjac#1]
After trying out the simpler examples like the calc, trying to run any of the applications in "Rich Widget Set" gives me this error:

A server error occurred. Please contact the administrator.

cheers

**Comment by rwl** [comment]
I thought this might come up!  Muntjac includes only the default widget set and the Sampler app requires some additional client-side code.  What to do is download both the DefaultWidgetSet and the SamplerWidgetSet to the same directory.

https://github.com/rwl/muntjac/downloads

Then point Muntjac to the directory containing the VAADIN folder:

$ muntjac --contextRoot=/path/to/VAADIN/directory

Not that this is not the VAADIN directory itself, but the directory containing it.  All this will be explained in the documentation in the next release.

**Comment by azazel75** [comment]
Hmmm, maybe you are misunderstanding... i was trying to run the applications linked into the http://www.muntiacus.org web site!

**Comment by rwl** [comment]
Ah, I did misunderstand.  Since announcing Muntjac on HackerNews my EC2 instance has been barraged with hits.  It might be a locale issue that you are having, but it is hard to say.  One thing you can try is deleting your muntiacus.org cookie and it should start a new session.

I have just restarted the server, but you can also try running Muntjac locally:

$ easy_install muntjac
$ muntjac --contextRoot=/path/to/VAADIN/directory
